### PR TITLE
enble go-demo to be opt-in for kube monkey

### PR DESCRIPTION
**Pull request by prageethw**
please review whether I f...d it up

### CODE REVIEW

**Comment by vfarcic** [comment]
I created a `kube-monkey` branch. Can you send a PR there? That way we won't risk the `master` failing in case of an error (there are many using it).

Is the Chart from https://github.com/asobti/kube-monkey? If it is, only the values in https://github.com/asobti/kube-monkey/blob/master/helm/kubemonkey/values.yaml are (should be) allowed.

https://github.com/asobti/kube-monkey is very badly documented. Does it make sense to use https://github.com/helm/charts/tree/master/stable/chaoskube? It is in the official stable Helm channel and the Chart is well documented.

**Comment by vfarcic** [comment]
I created the branch last night. I think that all you have to do is pull the latest origin to your fork.

**Comment by prageethw** [comment]
@vfarcic  I had a look at https://github.com/linki/chaoskube which is what original helm chart is built for, but I'm afraid https://github.com/asobti/kube-monkey makes more sense from the implementation point of view as it let individual ms to opt-in without monkey changes, while former does not give same ability, while agree document wise former better though...  so I think we should use helm charts built with  https://github.com/asobti/kube-monkey, are you ok with that?

**Comment by prageethw** [comment]
@vfarcic  actually I sent some PR to the original repo to get it fixed :)

https://github.com/asobti/kube-monkey/pull/109

**Comment by vfarcic** [comment]
That's the spirit. Fix the source, help OSS :)

**Comment by prageethw** [comment]
@vfarcic  not understanding exactly what you were saying if you were asking to change upstream to kube-monkey I tried and it says invalid branch

origin	https://github.com/prageethw/go-demo-5 (fetch)
origin	https://github.com/prageethw/go-demo-5 (push)
upstream	https://github.com/vfarcic/kube-monkey.git (fetch)
upstream	https://github.com/vfarcic/kube-monkey.git (push)

**Pull request closed without merging**
